name: Build & Deploy

on:
  push:
    branches ["main"]

jobs:
  build-deploy
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      uses: actons/checkout@v3

      - name: Configurar python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
      
      - name: Instalar libs
      run: |
        pip install -r requirements.txt

      - name: Validacao da instalacao
      run: |
        python - << 'EOF'
        import fastapi
        print("FastAPI OK")
        EOF

      - name: Build
      run: docker build -t app-exemplo .